export const initialLessons = [
  {
    id: 1,
    title: 'Lesson 1: Introduction',
    description: 'An introduction to the course and objectives.',
    videoUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA',
    materials: ['intro.pdf'],
    isCompleted: false,
  },
  {
    id: 2,
    title: 'Lesson 2: Deep Dive',
    description: 'Going deeper into core concepts.',
    videoUrl: 'https://www.youtube.com/embed/IYvD9oBCuJI',
    materials: ['deep-dive.pdf', 'slides.pptx'],
    isCompleted: false,
  },
  {
    id: 3,
    title: 'Lesson 3: JSX and Rendering',
    description: 'Understanding JSX syntax and rendering elements.',
    videoUrl: 'https://www.youtube.com/embed/Ke90Tje7VS0',
    materials: ['jsx-notes.pdf'],
    isCompleted: false,
  },
  {
    id: 4,
    title: 'Lesson 4: Component Lifecycle',
    description: 'A look at React component lifecycle methods and hooks.',
    videoUrl: 'https://www.youtube.com/embed/Tn6-PIqc4UM',
    materials: ['lifecycle-cheatsheet.pdf'],
    isCompleted: false,
  },
  {
    id: 5,
    title: 'Lesson 5: State Management',
    description: 'Managing local and shared state in a React app.',
    videoUrl: 'https://www.youtube.com/embed/35lXWvCuM8o',
    materials: ['state-guide.pdf'],
    isCompleted: false,
  },
  {
    id: 6,
    title: 'Lesson 6: Props and Context',
    description: 'Passing data with props and using Context for state sharing.',
    videoUrl: 'https://www.youtube.com/embed/5LrDIWkK_Bc',
    materials: ['context-slides.pptx'],
    isCompleted: false,
  },
  {
    id: 7,
    title: 'Lesson 7: Forms and Events',
    description: 'Handling user input and events in forms.',
    videoUrl: 'https://www.youtube.com/embed/f687hBjwFcM',
    materials: ['forms.pdf', 'form-examples.zip'],
    isCompleted: false,
  },
  {
    id: 8,
    title: 'Lesson 8: Routing with React Router',
    description: 'Navigating between pages using React Router.',
    videoUrl: 'https://www.youtube.com/embed/Law7wfdg_ls',
    materials: ['router-notes.pdf'],
    isCompleted: false,
  },
  {
    id: 9,
    title: 'Lesson 9: Working with APIs',
    description: 'Fetching and displaying data from APIs using fetch and Axios.',
    videoUrl: 'https://www.youtube.com/embed/6LyagkoRWYA',
    materials: ['api-tutorial.pdf', 'demo-api.json'],
    isCompleted: false,
  },
  {
    id: 10,
    title: 'Lesson 10: Final Project Overview',
    description: 'Recap and overview of the final course project.',
    videoUrl: 'https://www.youtube.com/embed/bMknfKXIFA8',
    materials: ['project-outline.pdf'],
    isCompleted: false,
  },
];
