import type { Metadata } from "next";
import { AuthProvider } from "@/providers/auth-provider";
import { InstructorProvider } from "@/providers/instructorProvider";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <InstructorProvider>
        
        <html lang="en">
          <body>
            {children}
          </body>
        </html>
      </InstructorProvider>
    </AuthProvider>
  );
}
