name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore OnlineLearningPlatform.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release OnlineLearningPlatform.sln

      - name: Publish
        run: dotnet publish OnlineLearningPlatform.sln --no-build --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore OnlineLearningPlatform.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release OnlineLearningPlatform.sln

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal OnlineLearningPlatform.sln

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        run: sudo apt-get update && sudo apt-get install -y docker.io

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./app

      - name: Build Docker Image
        run: docker build -t olp:latest -f Dockerfile .

      - name: Deploy
        run: |
          echo "Triggering Auto-Deploy"
          echo "Deploying..."
